// autogenerated by assets/convert.py

// lines at top, removed
#define SCREEN_TOP_CROP  15

extern const unsigned char screen_verify[];
extern const unsigned char screen_blankish[];
extern const unsigned char screen_fatal[];
extern const unsigned char screen_mitm[];
extern const unsigned char screen_brick[];
extern const unsigned char screen_downgrade[];
extern const unsigned char screen_corrupt[];
extern const unsigned char screen_logout[];
extern const unsigned char screen_poweroff[];
extern const unsigned char screen_devmode[];
extern const unsigned char screen_red_light[];
extern const unsigned char screen_upgrading[];
extern const unsigned char screen_search[];
extern const unsigned char screen_recovery[];
extern const unsigned char screen_se1_issue[];
extern const unsigned char screen_se2_issue[];
extern const unsigned char screen_wiped[];
extern const unsigned char screen_se_setup[];
