# (c) Copyright 2026 by Coinkite Inc. This file is covered by license found in COPYING-CC.
#
# test_musig2_sp_signers.py - Coldcard simulator tests for MuSig2 + Silent Payments.
#
# Test keeps three simulator processes alive so Alice, Bob, Charlie each perform both
# rounds and the last signer finalizes the transaction.
#
# Expected musig2-sp-final-tx.hex is generated by the Rust binary in bip375-examples:
#   cargo run -p musig2-signer --bin finalize <path-to-testing/data>
#
# Use CC_SP_OUT env var to capture debug artifacts (PSBTs, final transaction) from the test run.
# ex. export CC_SP_OUT=/tmp/cc-sp-out && pytest test_musig2_sp_signers.py


import io
import json
import os
import pytest
import shutil
import sys
import time
from binascii import b2a_hex
from ckcc_protocol.client import ColdcardDevice
from ckcc_protocol.protocol import CCProtocolPacker
from core_fixtures import _cap_story, _dev_hw_label, _need_keypress, _press_cancel, _press_select
from ctransaction import CTransaction, CTxOut
from helpers import xfp2str
from psbt import BasicPSBT
from run_sim_tests import ColdcardSimulator
from test_musig2_silentpayments import (
    NUM_RECIPIENTS,
    ROUND1_PSBT,
    TREASURY_DESC,
    _load_psbt,
    _get_scan_keys,
    _maybe_write_artifact,
)

DATA_DIR = os.path.join(os.path.dirname(__file__), "data")

SIGNER_XFPS = {
    "Alice": "0F056943",
    "Bob": "6BA6CFD0",
    "Charlie": "747B698E",
}
SIM_START_TIMEOUT = 15
SIM_START_POLL_INTERVAL = 0.5


def _exec_sim_file(device, path):
    full_path = os.path.abspath(path)
    hook = "execfile(%r)" % full_path
    rv = device.send_recv(b"EXEC" + hook.encode("utf-8"), timeout=60000, encrypt=False)
    rv = rv.decode("utf-8")
    assert "Traceback" not in rv, rv
    return rv


def _clear_sim_cache(device):
    cmd = "from psbt import MUSIG_SESSION_CACHE; MUSIG_SESSION_CACHE.clear()"
    rv = device.send_recv(b"EXEC" + cmd.encode("utf-8"), timeout=60000, encrypt=False)
    assert b"Traceback" not in rv, rv


def _activate_bip39_passphrase(device, is_q1, passphrase):
    """Activate a simulator BIP39 passphrase and refresh the encrypted USB session."""
    device.send_recv(CCProtocolPacker.bip39_passphrase(passphrase), timeout=None)
    time.sleep(0.1)

    _, story = _cap_story(device)
    assert "to master seed" in story
    _press_select(device, is_q1)

    time.sleep(0.3)
    _, story = _cap_story(device)
    if "Press (1) to store temporary seed into Seed Vault" in story:
        _press_select(device, is_q1)
        time.sleep(0.2)
        _, story = _cap_story(device)

    assert "Above is the master key fingerprint" in story
    _press_select(device, is_q1)

    done = None
    while done is None:
        time.sleep(0.05)
        done = device.send_recv(CCProtocolPacker.get_passphrase_done(), timeout=None)
    assert done[1:4] == "pub"

    device.start_encryption()
    device.check_mitm()


class HardwareSigner:
    """Device-bound operations needed by the two-round signing test."""

    def __init__(self, name, device, is_q1):
        self.name = name
        self.device = device
        self.is_q1 = is_q1

    def assert_fingerprint(self):
        got = xfp2str(self.device.master_fingerprint)
        assert got == SIGNER_XFPS[self.name], f"{self.name}: expected XFP {SIGNER_XFPS[self.name]}, got {got}"

    def clear_session_cache(self):
        _clear_sim_cache(self.device)

    def enroll_treasury(self):
        _exec_sim_file(self.device, "devtest/wipe_miniscript.py")
        with open(TREASURY_DESC) as f:
            desc = f.read().strip()
        config = json.dumps(dict(name="sp_treasury", desc=desc)).encode("ascii")
        file_len, sha = self.device.upload_file(config)
        self.device.send_recv(CCProtocolPacker.miniscript_enroll(file_len, sha))

        time.sleep(0.2)
        _, story = _cap_story(self.device)
        assert "Create new miniscript wallet?" in story
        _press_select(self.device, self.is_q1)
        time.sleep(0.1)

    def sign(self, psbt_bytes, expected_title, finalize=False):
        file_len, sha = self.device.upload_file(psbt_bytes)
        self.device.send_recv(CCProtocolPacker.sign_transaction(file_len, sha, finalize))

        title, story = _cap_story(self.device)
        assert title == expected_title, f"{self.name}: expected story {expected_title!r}, got {title!r}: {story}"

        _need_keypress(self.device, "y", timeout=None)
        done = None
        while done is None:
            done = self.device.send_recv(CCProtocolPacker.get_signed_txn(), timeout=None)
        result_len, checksum = done
        result = self.device.download_file(result_len, checksum)
        _press_cancel(self.device, self.is_q1)

        if finalize:
            assert not result.startswith(b"psbt\xff")
        else:
            assert result.startswith(b"psbt\xff")
        return result, story


def _start_child_simulator(simulator):
    """ColdcardSimulator uses bare `python`; make it resolve to pytest's interpreter."""
    old_path = os.environ.get("PATH", "")
    os.environ["PATH"] = os.path.dirname(sys.executable) + os.pathsep + old_path
    try:
        simulator.start(start_wait=SIM_START_POLL_INTERVAL)
    finally:
        os.environ["PATH"] = old_path

    try:
        deadline = time.monotonic() + SIM_START_TIMEOUT
        last_error = None
        while time.monotonic() < deadline:
            exit_code = simulator.proc.poll()
            if exit_code is not None:
                raise RuntimeError(f"Simulator exited before socket was ready: {simulator.socket} (exit={exit_code})")

            device = None
            try:
                device = ColdcardDevice(sn=simulator.socket, is_simulator=True)
                return
            except Exception as exc:
                last_error = exc
                time.sleep(SIM_START_POLL_INTERVAL)
            finally:
                if device is not None:
                    device.close()

        exit_code = simulator.proc.poll()
        status = "still running" if exit_code is None else f"exited with {exit_code}"
        raise RuntimeError(f"Simulator socket was not ready after {SIM_START_TIMEOUT}s: {simulator.socket} ({status})") from last_error
    except Exception:
        socket_path = simulator.socket
        work_path = f"/tmp/cc-simulators/{simulator.proc.pid}"
        simulator.stop()
        if os.path.exists(socket_path):
            os.unlink(socket_path)
        shutil.rmtree(work_path, ignore_errors=True)
        raise


@pytest.fixture
def three_musig_signers(request, is_headless):
    """
    Alice, Bob and Charlie each run in their own segregated simulator process so the test
    starts every simulator it needs (no pre-running simulator required) and each signer
    retains an independent MUSIG_SESSION_CACHE between Round 1 and Round 2.

    The hardware build matches the simulator run_sim_tests pre-starts (read via --sim-socket);
    a bare pytest run with no simulator defaults to Q1. Alice uses the fixed simulator seed
    (no passphrase); Bob and Charlie layer BIP39 passphrases to get distinct fingerprints.
    """
    sim_socket = request.config.getoption("--sim-socket")
    if sim_socket:
        probe = ColdcardDevice(sn=sim_socket, is_simulator=True)
        try:
            hw_label = _dev_hw_label(probe)
        finally:
            probe.close()
    else:
        hw_label = "q1" if request.config.getoption("--Q") else "mk%d" % int(request.config.getoption("--mk"))

    if hw_label == "q1":
        args = ["--q1"]
    elif hw_label == "mk4":
        args = ["--mk4"]
    elif hw_label == "mk5":
        args = []
    else:
        pytest.skip(f"Three-simulator MuSig2 test does not support {hw_label}")
    is_q1 = hw_label == "q1"

    signers = []
    simulators = []

    try:
        for name, passphrase in [("Alice", None), ("Bob", "Me"), ("Charlie", "Myself")]:
            simulator = ColdcardSimulator(
                args=list(args),
                headless=is_headless,
                segregate=True,
            )
            _start_child_simulator(simulator)
            simulators.append(simulator)
            device = ColdcardDevice(sn=simulator.socket, is_simulator=True)
            signer = HardwareSigner(name, device, is_q1)
            signers.append(signer)
            if passphrase is not None:
                _activate_bip39_passphrase(device, is_q1, passphrase)

        for signer in signers:
            assert _dev_hw_label(signer.device) == hw_label
            signer.assert_fingerprint()
            signer.clear_session_cache()
            signer.enroll_treasury()

        yield signers
    finally:
        for signer in reversed(signers):
            signer.device.close()
        for simulator in reversed(simulators):
            socket_path = simulator.socket
            work_path = f"/tmp/cc-simulators/{simulator.proc.pid}"
            simulator.stop()
            if os.path.exists(socket_path):
                os.unlink(socket_path)
            shutil.rmtree(work_path, ignore_errors=True)


def _assert_round1_contribution(before, after, signer_name, scan_keys):
    """Assert and return the participant key added by one hardware signer."""
    before_inp = before.inputs[0]
    after_inp = after.inputs[0]

    new_pubnonces = set(after_inp.musig_pubnonces) - set(before_inp.musig_pubnonces)
    new_ecdh = set(after_inp.musig_partial_ecdh_shares) - set(before_inp.musig_partial_ecdh_shares)
    new_dleq = set(after_inp.musig_partial_dleq_proofs) - set(before_inp.musig_partial_dleq_proofs)

    assert len(new_pubnonces) == 1, f"{signer_name}: expected one new pubnonce, got {len(new_pubnonces)}"
    participant_keys = {pk for _, pk in new_ecdh}
    assert len(participant_keys) == 1, f"{signer_name}: expected one ECDH participant key, got {len(participant_keys)}"
    (participant_key,) = participant_keys

    (nonce_key,) = new_pubnonces
    assert nonce_key[0] == participant_key
    assert {sk for sk, pk in new_ecdh if pk == participant_key} == scan_keys
    assert {sk for sk, pk in new_dleq if pk == participant_key} == scan_keys
    assert len(new_ecdh) == len(scan_keys)
    assert len(new_dleq) == len(scan_keys)

    assert len(after_inp.musig_pubnonces[nonce_key]) == 66
    for key in new_ecdh:
        share = after_inp.musig_partial_ecdh_shares[key]
        assert len(share) == 33 and share[0] in (0x02, 0x03)
    for key in new_dleq:
        assert len(after_inp.musig_partial_dleq_proofs[key]) == 64

    assert not after_inp.musig_part_sigs
    assert not after_inp.taproot_key_sig
    return participant_key


def _sp_scripts(tp):
    return [bytes(out.script) for out in tp.outputs if out.sp_v0_info]


def _assert_partial_sigs(tp, participant_keys, expected_names):
    inp = tp.inputs[0]
    assert len(inp.musig_part_sigs) == len(expected_names)
    expected_keys = {participant_keys[name] for name in expected_names}
    actual_keys = {pk for pk, _ak, _lh in inp.musig_part_sigs}
    assert actual_keys == expected_keys
    assert all(len(sig) == 32 for sig in inp.musig_part_sigs.values())
    assert not inp.taproot_key_sig


def _assert_complete_psbt(tp, participant_keys):
    """The final signer's PSBT: all three partial sigs plus the aggregated taproot key sig."""
    inp = tp.inputs[0]
    assert len(inp.musig_part_sigs) == len(participant_keys)
    actual_keys = {pk for pk, _ak, _lh in inp.musig_part_sigs}
    assert actual_keys == set(participant_keys.values())
    assert all(len(sig) == 32 for sig in inp.musig_part_sigs.values())

    assert inp.taproot_key_sig, "final signer must aggregate the taproot key sig"
    # 64-byte Schnorr sig, or 65 bytes when a sighash flag is appended
    assert len(inp.taproot_key_sig) in (64, 65)


def _parse_transaction(raw):
    tx = CTransaction()
    tx.deserialize(io.BytesIO(raw))
    return tx


def _parse_txout(raw):
    txout = CTxOut()
    txout.deserialize(io.BytesIO(raw))
    return txout


def _assert_final_transaction(raw_tx, expected_psbt):
    actual = _parse_transaction(raw_tx)

    expected_version = 2 if expected_psbt.txn_version is None else expected_psbt.txn_version
    expected_locktime = 0 if expected_psbt.fallback_locktime is None else expected_psbt.fallback_locktime
    assert actual.nVersion == expected_version
    assert actual.nLockTime == expected_locktime
    assert len(actual.vin) == 1
    assert len(actual.vout) == len(expected_psbt.outputs)

    expected_input = expected_psbt.inputs[0]
    actual_input = actual.vin[0]
    assert actual_input.prevout.hash == int.from_bytes(expected_input.previous_txid, "little")
    assert actual_input.prevout.n == expected_input.prevout_idx
    assert actual_input.scriptSig == b""
    expected_sequence = 0xffffffff if expected_input.sequence is None else expected_input.sequence
    assert actual_input.nSequence == expected_sequence

    expected_outputs = [(out.amount, out.script) for out in expected_psbt.outputs]
    actual_outputs = [(out.nValue, out.scriptPubKey) for out in actual.vout]
    assert actual_outputs == expected_outputs

    witness_utxo = _parse_txout(expected_input.witness_utxo)
    assert sum(out.nValue for out in actual.vout) < witness_utxo.nValue

    sp_outputs = [out for out in expected_psbt.outputs if out.sp_v0_info]
    change_outputs = [out for out in expected_psbt.outputs if not out.sp_v0_info]
    assert len(sp_outputs) == NUM_RECIPIENTS
    assert len(change_outputs) == 1
    assert all(out.script and len(out.script) == 34 and out.script[0] == 0x51 for out in sp_outputs)

    assert len(actual.wit.vtxinwit) == 1
    witness = actual.wit.vtxinwit[0].scriptWitness.stack
    assert len(witness) == 1
    assert len(witness[0]) == 64


# ---------------------------------------------------------------------------
# Test
# ---------------------------------------------------------------------------


@pytest.mark.parametrize("finalize_on_device", [True, False], ids=["final-txn", "signed-psbt"])
def test_musig2_sp_three_hardware_signers(three_musig_signers, finalize_on_device):
    """
    End-to-end hardware workflow:

      Round 1: Alice -> Bob -> Charlie each add a pubnonce and SP ECDH/DLEQ shares.
      Round 2: Alice -> Bob add partial signatures; Charlie adds the third partial and
               aggregates the MuSig2 signature.

    Charlie's last step runs as one of two cases (CC finalizes only as part of the final
    signature, and his nonce is one-shot, so each output needs its own fresh run):
      - finalize_on_device=True : Charlie signs with finalize=True -> broadcast-ready txn.
      - finalize_on_device=False: Charlie signs with finalize=False -> fully-signed PSBT.
    """
    if not all(os.path.exists(path) for path in (ROUND1_PSBT, TREASURY_DESC)):
        pytest.skip(f"Three-signer fixtures not found at {DATA_DIR}")

    signers = three_musig_signers
    current = BasicPSBT().parse(_load_psbt(ROUND1_PSBT))
    scan_keys = _get_scan_keys(current)
    assert len(scan_keys) == NUM_RECIPIENTS

    participant_keys = {}

    # Round 1: pass the growing PSBT through three independent hardware devices.
    for expected_count, signer in enumerate(signers, start=1):
        before = current
        expected_title = "OK TO SEND?" if expected_count == len(signers) else "CONTRIBUTE SHARES?"
        signed, story = signer.sign(
            before.as_bytes(),
            expected_title=expected_title,
            finalize=False,
        )
        if expected_title == "CONTRIBUTE SHARES?":
            assert "ECDH shares" in story
            assert "Other signers" in story
        else:
            # Charlie's shares complete ECDH coverage during preview, but his empty device
            # session cache still makes this approval cryptographic Round 1.
            assert "sp1" in story

        current = BasicPSBT().parse(signed)
        _maybe_write_artifact(signed, f"r1-{signer.name.lower()}.psbt")
        participant_keys[signer.name] = _assert_round1_contribution(before, current, signer.name, scan_keys)
        assert len(current.inputs[0].musig_pubnonces) == expected_count
        assert len(current.inputs[0].musig_partial_ecdh_shares) == expected_count * NUM_RECIPIENTS
        assert len(current.inputs[0].musig_partial_dleq_proofs) == expected_count * NUM_RECIPIENTS

    assert len(set(participant_keys.values())) == 3
    assert len(current.inputs[0].musig_pubnonces) == 3
    assert len(current.inputs[0].musig_partial_ecdh_shares) == 3 * NUM_RECIPIENTS
    assert len(current.inputs[0].musig_partial_dleq_proofs) == 3 * NUM_RECIPIENTS

    # Round 2: Alice derives the SP scripts and signs; Bob verifies and signs the same PSBT.
    round2_psbt = current
    expected_scripts = None
    for expected_count, signer in enumerate(signers[:2], start=1):
        signed, story = signer.sign(
            round2_psbt.as_bytes(),
            expected_title="OK TO SEND?",
            finalize=False,
        )
        assert "sp1" in story

        round2_psbt = BasicPSBT().parse(signed)
        _maybe_write_artifact(signed, f"r2-{signer.name.lower()}.psbt")
        _assert_partial_sigs(
            round2_psbt,
            participant_keys,
            [s.name for s in signers[:expected_count]],
        )

        scripts = _sp_scripts(round2_psbt)
        assert len(scripts) == NUM_RECIPIENTS
        assert all(len(script) == 34 and script[0] == 0x51 for script in scripts)
        if expected_scripts is None:
            expected_scripts = scripts
        else:
            assert scripts == expected_scripts

    # Charlie consumes the last secret nonce, adds the final partial, and aggregates the
    # MuSig2 signature.
    charlie = signers[2]
    result, story = charlie.sign(
        round2_psbt.as_bytes(),
        expected_title="OK TO SEND?",
        finalize=finalize_on_device,
    )
    assert "sp1" in story

    if finalize_on_device:
        # Charlie finalizes in the same pass: broadcast-ready transaction.
        _maybe_write_artifact(b2a_hex(result) + b"\n", "musig2-sp-final.hex")
        _assert_final_transaction(result, round2_psbt)
    else:
        # Charlie exports the fully-signed PSBT (all three partials + aggregated key sig).
        complete_psbt = BasicPSBT().parse(result)
        _maybe_write_artifact(result, "musig2-sp-final.psbt")
        _assert_complete_psbt(complete_psbt, participant_keys)
        scripts = _sp_scripts(complete_psbt)
        assert len(scripts) == NUM_RECIPIENTS
        assert scripts == expected_scripts
