freeze_as_mpy('', [
	'aes256ctr.py',
	'bare_metal.py',
	'ckcc.py',
	'ffilib.py',
	'machine.py',
	'mock.py',
	'os.py',
	'pyb.py',
	'sim_mk4.py',
	'sim_battery.py',
	'sim_scanner.py',
	'sim_nfc.py',
	'sim_psram.py',
	'sim_quickstart.py',
	'sim_secel.py',
	'sim_se2.py',
	'sim_settings.py',
	'sim_vdisk.py',
	'ssd1306.py',
	'st7788.py',
	'gpu.py',
	'stm.py',
	'struct.py',
	'touch.py',
	'version.py',
	'zevvpeep.py',
], opt=0)
#include("../../shared/manifest_mk4.py")
include("$(MPY_DIR)/extmod/uasyncio/manifest.py")

