freeze_as_mpy('', [
	'bare_metal.py',
	'ckcc.py',
	'ffilib.py',
	'machine.py',
	'mock.py',
	'os.py',
	'pyb.py',
	'sflash.py',
	'sim_display.py',
	'sim_quickstart.py',
	'main2.py',
	'sim_secel.py',
	'sim_settings.py',
	'sram2.py',
	'ssd1306.py',
	'stm.py',
	'struct.py',
	'touch.py',
	'usb_test_commands.py',
	'version.py',
	'aes256ctr.py',
	'zevvpeep.py',
	'mk4.py',
	'sim_psram.py',
	'sim_nfc.py',
], opt=0)
#include("../../shared/manifest_mk4.py")
include("$(MPY_DIR)/extmod/uasyncio/manifest.py")

