# (c) Copyright 2021 by Coinkite Inc. This file is covered by license found in COPYING-CC.
#
# Placeholder for lazy devs.
#
# In general, use:
#	make -f MK4-Makefile
# or
#	make -f MK3-Makefile
#

include MK4-Makefile
#include MK3-Makefile
